version: '2.1'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - './postgresql:/docker-entrypoint-initdb.d'